### ISSUE TITLE
No visible setting change for dealing dealt cards onto canvas

### ISSUE THREAD

**Issue by QuestionQuest117** [alessiocali/card-tiles#14]
I don't know if I'm stupid, but I can't find any settings for enabling cards that have been dealt to be placed onto the canvas. It says to look in settings, but I see no such setting for it in module settings for Card Tiles or Monk's Active Tile Triggers, and I don't see it in the settings for the canvas, decks, or cards.

Where can this be found and disabled? It makes it a lot more complicated if you can't just play a card from your hand by dragging it onto the canvas.

**Comment by alessiocali** [comment]
I noticed it myself some time ago during a play test, but didn't have the time to go and fix it. I will try to give it a look when I have some spare time.
