### ISSUE TITLE
Bug: Card tiles won't flip

### ISSUE THREAD

**Issue by SalieriC** [alessiocali/card-tiles#23]
As of v.0.1.0 the card tiles can't be flipped anymore. There seems to be some problem with how the flags for MATT are created. When using tile controls and trying to open the card tile the console shows the following error:
![image](https://user-images.githubusercontent.com/1230041/179919013-da7f50ef-9718-4b8f-a2cc-31f75fce4d15.png)
This worked flawlessly before. But I'm yet unfamiliar with how MATT flags need to be structured .

**Comment by SalieriC** [comment]
Nevermind, should've updated MATT. Sorry about that.

**Comment by alessiocali** [comment]
Yeah I wish we could specify a minimum required version for dependencies too, but I don't think it's part of the manifest.
