### ISSUE TITLE
Cannot pull actors to canvas.

### ISSUE THREAD

**Issue by Lordofallic** [alessiocali/card-tiles#26]
I noticed that I could not drag and drop any actors to the scene.  They would disappear as soon as I dropped them.  I found that, by process of elimination, the card-tiles module was the culprit.  Oh and this was using latest Foundry and latest SWADE Deadlands build.  I hope you can fix it soon because it is a GREAT module and I prefer it to all the others.

**Comment by alessiocali** [comment]
From what I see the DragDrop API received some updates so maybe now there's a less barbaric way than what I did before. I'll try to have it a look later today or tomorrow.

**Comment by alessiocali** [comment]
Version 0.2.2 should have fixed this, unfortunately I still had to resort to the same barbaric method because the element filter added to the DragDrop configuration did not act the way I hoped. Still, it works, until the next API break.
